# Generated by Django 3.2.16 on 2022-12-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('spice', models.FloatField(blank=True, null=True)),
                ('raw_spice', models.FloatField(blank=True, null=True)),
                ('popular', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charts',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'difficulties',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorebrowser.difficulty'),
        ),
        migrations.AddField(
            model_name='chart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorebrowser.song'),
        ),
    ]
