# Generated by Django 3.2.16 on 2022-12-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.TextField()),
            ],
        ),
    ]
