# Generated by Django 3.2.16 on 2022-12-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0007_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scorebrowser.version'),
        ),
    ]
