# Generated by Django 3.2.16 on 2022-12-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0009_song_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
