# Generated by Django 3.2.16 on 2022-12-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0012_auto_20221206_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
