# Generated by Django 3.2.16 on 2023-01-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0013_auto_20221213_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='UnprocessedPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_u', to='scorebrowser.chart')),
                ('y_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_u', to='scorebrowser.chart')),
            ],
            options={
                'db_table': 'unprocessed_pairs',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.chart')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.player')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='ChartPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slope', models.FloatField()),
                ('strength', models.FloatField()),
                ('x_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x', to='scorebrowser.chart')),
                ('y_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y', to='scorebrowser.chart')),
            ],
            options={
                'db_table': 'chart_pairs',
            },
        ),
    ]
