from django.db import migrations, models


def forward(apps, schema_editor):
	UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
	UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
	ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
	Song = apps.get_model("scorebrowser", "Song")
	Chart = apps.get_model("scorebrowser", "Chart")
	Difficulty = apps.get_model("scorebrowser", "Difficulty")

	def findChart(title, difficulty_id):
		return Chart.objects.filter(song__title=title, difficulty_id=difficulty_id).first()

	extraExclusives = UnlockEvent.objects.create(name="EXTRA EXCLUSIVE", ordering=-1, completable=False)
	extraExclusive = UnlockTask.objects.create(event=extraExclusives, name="EXTRA EXCLUSIVE", ordering=-1)
	ChartUnlock.objects.create(version_id=19, task=extraExclusive, chart=findChart("Deep tenDon Reflex", 3), extra=True)
	ChartUnlock.objects.create(version_id=19, task=extraExclusive, chart=findChart("Deep tenDon Reflex", 4), extra=True)
	ChartUnlock.objects.create(version_id=19, task=extraExclusive, chart=findChart("THE ANCIENT KING IS BACK", 3), extra=True)
	ChartUnlock.objects.create(version_id=18, task=extraExclusive, chart=findChart("Last Card", 3), extra=True)
	ChartUnlock.objects.create(version_id=18, task=extraExclusive, chart=findChart("ANTI ANTHEM", 3), extra=True)

	goldenLeaguePlus = UnlockEvent.objects.create(name="GOLDEN LEAGUE PLUS", ordering=1)
	bronzePlus = UnlockTask.objects.create(event=goldenLeaguePlus, name='BRONZE CLASS', ordering=10)
	ChartUnlock.objects.create(version_id=18, task=bronzePlus, chart=findChart('Lightspeed', 3))
	ChartUnlock.objects.create(version_id=18, task=bronzePlus, chart=findChart('Run The Show', 3))
	ChartUnlock.objects.create(version_id=18, task=bronzePlus, chart=findChart("Yuni's Nocturnal Days", 3))
	ChartUnlock.objects.create(version_id=18, task=bronzePlus, chart=findChart('Good Looking', 3))
	silverPlus = UnlockTask.objects.create(event=goldenLeaguePlus, name='SILVER CLASS', ordering=20)
	ChartUnlock.objects.create(version_id=18, task=silverPlus, chart=findChart("Step This Way", 3))
	ChartUnlock.objects.create(version_id=18, task=silverPlus, chart=findChart("Come Back To Me", 3))
	ChartUnlock.objects.create(version_id=18, task=silverPlus, chart=findChart("actualization of self (weaponized)", 3))
	ChartUnlock.objects.create(version_id=18, task=silverPlus, chart=findChart("Better Than Me", 3))
	goldPlus = UnlockTask.objects.create(event=goldenLeaguePlus, name='GOLD CLASS', ordering=30)
	ChartUnlock.objects.create(version_id=18, task=goldPlus, chart=findChart("DDR TAGMIX -LAST DanceR-", 2))
	ChartUnlock.objects.create(version_id=18, task=goldPlus, chart=findChart("DDR TAGMIX -LAST DanceR-", 3))
	ChartUnlock.objects.create(version_id=18, task=goldPlus, chart=findChart("THIS IS MY LAST RESORT", 3))

	def createExtraSavior(version_id, event, title, difficulty_id, taskOrdering):
		difficulty = Difficulty.objects.filter(id=difficulty_id).first()
		chart = findChart(title, difficulty_id)
		task = UnlockTask.objects.create(event=event, name='{} ({} {})'.format(title, difficulty.name, chart.rating), ordering=taskOrdering)
		ChartUnlock.objects.create(version_id=version_id, task=task, chart=chart, extra=True)
		return task   # used for events where you get a bonus song for unlocking everything

	extraSaviorPlus = UnlockEvent.objects.create(name="EXTRA SAVIOR PLUS", ordering=19)
	createExtraSavior(18, extraSaviorPlus, 'City Never Sleeps', 3, 10)
	createExtraSavior(18, extraSaviorPlus, 'Riot of Color', 3, 20)
	createExtraSavior(18, extraSaviorPlus, '東京神話', 3, 30)

	bandMeshi2 = UnlockEvent.objects.create(name="バンめし♪ ふるさとグランプリ ROUND 2", ordering=20)
	createExtraSavior(18, bandMeshi2, 'アリスサイド・キャスリング', 3, 10)
	createExtraSavior(18, bandMeshi2, '花は折りたし梢は高し', 3, 20)
	createExtraSavior(18, bandMeshi2, '叛逆のディスパレート', 3, 30)
	createExtraSavior(18, bandMeshi2, '追憶のアリア', 3, 40)

	bandMeshi3 = UnlockEvent.objects.create(name="バンめし♪ ふるさとグランプリ ROUND 3", ordering=30)
	createExtraSavior(18, bandMeshi3, 'Red Cape Theorem', 3, 10)
	createExtraSavior(18, bandMeshi3, 'イノセントバイブル', 3, 20)
	createExtraSavior(18, bandMeshi3, 'ハラショー！おにぎりサーカス団☆', 3, 30)
	createExtraSavior(18, bandMeshi3, 'ウソツキ横丁は雨模様', 3, 40)

	trickHalloween = UnlockEvent.objects.create(name="Trick and DDR! HAPPY HALLOWEEN!!", ordering=40)
	createExtraSavior(18, trickHalloween, 'DEADLOCK -Out Of Reach-', 3, 10)
	createExtraSavior(18, trickHalloween, 'GHOST KINGDOM', 3, 20)

	christmas2020 = UnlockEvent.objects.create(name="Merry Christmas and Happy DDR! 2020", ordering=50)
	createExtraSavior(18, christmas2020, 'BRIDAL FESTIVAL !!!', 3, 10)
	createExtraSavior(18, christmas2020, 'Never See You Again', 3, 20)

	valentine2021 = UnlockEvent.objects.create(name="恋せよDDRのバレンタイン＆ホワイトデー2021", ordering=60)
	createExtraSavior(18, valentine2021, 'BITTER CHOCOLATE STRIKER', 3, 10)
	createExtraSavior(18, valentine2021, "We're so Happy", 3, 20)

	springFestival = UnlockEvent.objects.create(name='花咲ケ!DDR SPRING FESTIVAL', ordering=70)
	createExtraSavior(18, springFestival, 'Evans', 2, 10)
	createExtraSavior(18, springFestival, 'Evans', 3, 20)
	createExtraSavior(18, springFestival, 'Hella Deep', 3, 30)

	over200 = UnlockEvent.objects.create(name="OVER 200", ordering=80)
	createExtraSavior(18, over200, 'ONYX', 3, 10)
	createExtraSavior(18, over200, "Poppin' Soda", 3, 20)
	createExtraSavior(18, over200, 'Sword of Vengeance', 3, 30)
	createExtraSavior(18, over200, 'High & Low', 3, 40)
	createExtraSavior(18, over200, 'paparazzi', 3, 50)
	createExtraSavior(18, over200, '勇猛無比', 3, 60)
	createExtraSavior(18, over200, 'BLAKE', 3, 70)
	createExtraSavior(18, over200, 'Shout It Out', 3, 80)
	createExtraSavior(18, over200, 'ノープラン・デイズ', 3, 90)
	createExtraSavior(18, over200, 'TYPHØN', 2, 100)
	createExtraSavior(18, over200, 'TYPHØN', 3, 110)

	valentine2022 = UnlockEvent.objects.create(name='恋せよDDRのバレンタイン＆ホワイトデー2022', ordering=90)
	createExtraSavior(18, valentine2022, 'jet coaster☆girl', 3, 10)

	summerCamp = UnlockEvent.objects.create(name="DANCERUSH STARDOM × DanceDanceRevolution SUMMER DANCE CAMP 2020", ordering=100)
	createExtraSavior(18, summerCamp, 'DANCERUSH STARDOM ANTHEM', 3, 10)
	createExtraSavior(18, summerCamp, 'take me higher', 3, 20)
	createExtraSavior(18, summerCamp, 'Midnight Amaretto', 3, 30)

	bemaniRush = UnlockEvent.objects.create(name="毎週！いちかの超BEMANIラッシュ2020", ordering=110)
	createExtraSavior(18, bemaniRush, "Our Love", 3, 10)
	createExtraSavior(18, bemaniRush, "Last Twilight", 3, 20)
	createExtraSavior(18, bemaniRush, "蒼が消えるとき", 3, 30)
	createExtraSavior(18, bemaniRush, "ノルエピネフリン", 3, 40)
	createExtraSavior(18, bemaniRush, "PANIC HOLIC", 3, 50)
	createExtraSavior(18, bemaniRush, "HARD BRAIN", 3, 60)
	createExtraSavior(18, bemaniRush, "Sparkle Smilin'", 3, 70)
	createExtraSavior(18, bemaniRush, "狂水一華", 3, 80)
	createExtraSavior(18, bemaniRush, "Jetcoaster Windy", 3, 90)

	def songUnlock(version_id, event, taskName, title, difficulty_ids, taskOrdering):
		task = UnlockTask.objects.create(event=event, name=taskName, ordering=taskOrdering)
		for difficulty_id in difficulty_ids:
			chart = Chart.objects.filter(song__title=title, difficulty_id=difficulty_id).first()
			ChartUnlock.objects.create(version_id=version_id, task=task, chart=chart)

	floorInfection = UnlockEvent.objects.create(name="FLOOR INFECTION", ordering=120)
	songUnlock(18, floorInfection, "Level 1 MAX (ΩVERSOUL)", "ΩVERSOUL", [3, 4], 10)
	songUnlock(18, floorInfection, "Level 2 MAX (Firestorm)", "Firestorm", [3, 4], 10)
	songUnlock(18, floorInfection, "Level 3 MAX (Lachryma《Re:Queen’M》)", "Lachryma《Re:Queen’M》", [2, 3, 4], 10)

	challengeCarnival = UnlockEvent.objects.create(name="DDR CHALLENGE Carnival PLUS", ordering=130)
	songUnlock(18, challengeCarnival, "1 stamp (Shiny World)", "Shiny World", [4], 10)
	songUnlock(18, challengeCarnival, "3 stamps (Sakura Sunrise)", "Sakura Sunrise", [4], 10)
	songUnlock(18, challengeCarnival, "5 stamps (Pierce The Sky)", "Pierce The Sky", [4], 10)
	songUnlock(18, challengeCarnival, "8 stamps (バンブーソード・ガール)", "バンブーソード・ガール", [4], 10)
	songUnlock(18, challengeCarnival, "12 stamps (HyperTwist)", "HyperTwist", [4], 10)
	songUnlock(18, challengeCarnival, "16 stamps (Firestorm)", "Firestorm", [4], 10)
	songUnlock(18, challengeCarnival, "20 stamps (ΩVERSOUL)", "ΩVERSOUL", [4], 10)
	songUnlock(18, challengeCarnival, "24 stamps (び)", "び", [4], 10)
	songUnlock(18, challengeCarnival, "28 stamps (Lachryma《Re:Queen’M》)", "Lachryma《Re:Queen’M》", [4], 10)

	courseTrial = UnlockEvent.objects.create(name="COURSE TRIAL", ordering=10)  # deliberately at the top, after GL
	songUnlock(18, courseTrial, "STRANGE", "Bang Pad(Werk Mix)", [3], 10)
	songUnlock(18, courseTrial, "REMIXES", "Inner Spirit -GIGA HiTECH MIX-", [3], 20)
	songUnlock(18, courseTrial, "RAVE", "Rave Accelerator", [3], 30)
	songUnlock(18, courseTrial, "DIVA", "Twinkle Wonderland", [3], 40)
	songUnlock(18, courseTrial, "AGGRESSIVE", "Vertigo", [3], 50)
	songUnlock(18, courseTrial, "SNOW WHITE", "梅雪夜", [3], 60)
	songUnlock(18, courseTrial, "PARTY ANTHEMS", "PARTY ALL NIGHT(DJ KEN-BOW MIX)", [3], 70)
	songUnlock(18, courseTrial, "FANTASY", "彼方のリフレシア", [3], 80)
	songUnlock(18, courseTrial, "NIGHT DRIVE", "Next Phase", [3], 90)
	songUnlock(18, courseTrial, "FUTURE", "If", [3], 100)
	songUnlock(18, courseTrial, "JUST = 135", "Taking It To The Sky (PLUS step)", [3], 110)
	songUnlock(18, courseTrial, "TRIBAL", "Jucunda Memoria", [2, 3], 120)
	songUnlock(18, courseTrial, "SWEETS HOPPING", "Sweet Clock", [3], 130)
	songUnlock(18, courseTrial, "MACHINE", "AI", [3], 140)
	songUnlock(18, courseTrial, "STELLA", "ほしのつくりかた", [3], 150)
	songUnlock(18, courseTrial, "NEW STRADE", "モノクロモーメント", [3], 160)
	songUnlock(18, courseTrial, "KA・TA・KA・NA YEAH!", "パピポペピプペパ", [3], 170)
	songUnlock(18, courseTrial, "WITHSTAND", "SCHWARZSCHILD FIELD", [3], 180)
	songUnlock(18, courseTrial, "Let's DANCE!", "私をディスコに連れてって TOKYO", [3], 190)

	kac10 = UnlockEvent.objects.create(name="The 10th KONAMI Arcade Championship Entry Song", ordering=150)
	songUnlock(18, kac10, "Entered KAC 10", "世界の果てに約束の凱歌を -DDR Extended Megamix-", [2, 3], 10)

	bplRally = UnlockEvent.objects.create(name="BPL応援 楽曲解禁スタンプラリー", ordering=160)
	songUnlock(18, bplRally, "First Stage", "Uh-Oh", [3], 10)
	songUnlock(18, bplRally, "Second Stage", "灼熱 Pt.2 Long Train Running", [3], 20)

	midsummer = UnlockEvent.objects.create(name="BEMANI 2021真夏の歌合戦5番勝負", ordering=170)
	songUnlock(18, midsummer, "鋳鉄の檻", "鋳鉄の檻", [3], 10)
	songUnlock(18, midsummer, "MOVE! (We Keep It Movin')", "MOVE! (We Keep It Movin')", [3], 20)
	songUnlock(18, midsummer, "LIKE A VAMPIRE", "LIKE A VAMPIRE", [3], 30)
	songUnlock(18, midsummer, "スーパー戦湯ババンバーン", "スーパー戦湯ババンバーン", [3], 40)
	songUnlock(18, midsummer, "Globe Glitter", "Globe Glitter", [3], 50)
	songUnlock(18, midsummer, "ユメブキ", "ユメブキ", [3], 60)

	################# A3 starts here
	newChallengeChartsGroup = UnlockEvent.objects.create(name="New Challenge charts (A3)", ordering=-2, completable=False)
	newChallengeCharts = UnlockTask.objects.create(event=newChallengeChartsGroup, name="New Challenge charts (A3)", ordering=10)
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("Avenger", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("New Era", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("Give Me", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("Ace out", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("The World Ends Now", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("Rampage Hero", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("ALPACORE", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("シル・ヴ・プレジデント", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("灼熱Beach Side Bunny", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("SHINY DAYS", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("なだめスかし Negotiation", 4))
	ChartUnlock.objects.create(version_id=18, task=newChallengeCharts, chart=findChart("BITTER CHOCOLATE STRIKER", 4))

	goldenLeagueA3 = UnlockEvent.objects.create(name="GOLDEN LEAGUE A3", ordering=2)  # deliberately putting GL at the top.
	bronzeA3 = UnlockTask.objects.create(event=goldenLeagueA3, name='BRONZE CLASS', ordering=10)
	ChartUnlock.objects.create(version_id=19, task=bronzeA3, chart=findChart("DDR TAGMIX -LAST DanceR-", 2))
	ChartUnlock.objects.create(version_id=19, task=bronzeA3, chart=findChart("DDR TAGMIX -LAST DanceR-", 3))
	ChartUnlock.objects.create(version_id=19, task=bronzeA3, chart=findChart("THIS IS MY LAST RESORT", 3))
	ChartUnlock.objects.create(version_id=19, task=bronzeA3, chart=findChart('STAY GOLD', 3))
	ChartUnlock.objects.create(version_id=19, task=bronzeA3, chart=findChart('Teleportation', 3))
	silverA3 = UnlockTask.objects.create(event=goldenLeagueA3, name='SILVER CLASS', ordering=20)
	ChartUnlock.objects.create(version_id=19, task=silverA3, chart=findChart('Environ [De-SYNC] (feat. lythe)', 3))
	ChartUnlock.objects.create(version_id=19, task=silverA3, chart=findChart('Let Me Know', 3))
	ChartUnlock.objects.create(version_id=19, task=silverA3, chart=findChart('Let Me Show You', 3))
	ChartUnlock.objects.create(version_id=19, task=silverA3, chart=findChart('Go To The Oasis', 3))
	goldA3 = UnlockTask.objects.create(event=goldenLeagueA3, name='GOLD CLASS (or SILVER with advanced border)', ordering=30)
	ChartUnlock.objects.create(version_id=19, task=goldA3, chart=findChart('TAKE ME HIGHER', 3))
	advanceBorder = UnlockTask.objects.create(event=goldenLeagueA3, name='GOLD CLASS with advanced border', ordering=40)
	ChartUnlock.objects.create(version_id=19, task=advanceBorder, chart=findChart('Lose Your Sense', 3))

	extraSaviorA3 = UnlockEvent.objects.create(name='EXTRA SAVIOR A3', ordering=180)
	createExtraSavior(19, extraSaviorA3, "Good Sound United", 3, 10)
	createExtraSavior(19, extraSaviorA3, "Unreality", 3, 10)

	summerVacation = UnlockEvent.objects.create(name='Enjoy Summer Vacation!', ordering=190)
	createExtraSavior(19, summerVacation, "リリーゼと炎龍レーヴァテイン", 3, 10)
	createExtraSavior(19, summerVacation, "MANA", 3, 20)

	midsummerRedux = UnlockEvent.objects.create(name='BEMANI 2021真夏の歌合戦5番勝負 [A3]', ordering=200)
	midsummerTasks = []
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "鋳鉄の檻", 3, 1))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "MOVE! (We Keep It Movin')", 3, 2))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "LIKE A VAMPIRE", 3, 3))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "スーパー戦湯ババンバーン", 3, 4))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "Globe Glitter", 3, 5))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "ユメブキ", 3, 6))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "MA・TSU・RI", 3, 10))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "チュッチュ♪マチュピチュ", 3, 20))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "斑咲花", 3, 30))
	midsummerTasks.append(createExtraSavior(19, midsummerRedux, "DUAL STRIKER", 3, 40))
	midsummerTasks.append(UnlockTask.objects.create(event=midsummerRedux, name='All of the above, on doubles', ordering=50))
	finalTrack = findChart("恋愛観測 -2021真夏のエンディング ver.-", 3)
	for task in midsummerTasks:
		ChartUnlock.objects.create(version_id=19, task=task, chart=finalTrack)

	crystalClearWinter = UnlockEvent.objects.create(name='Crystal clear winter', ordering=210)
	createExtraSavior(19, crystalClearWinter, "Snow Garland Fairy", 3, 20)

	valentine2023 = UnlockEvent.objects.create(name='恋せよDDRのバレンタイン＆ホワイトデー2023', ordering=220)
	createExtraSavior(19, valentine2023, "みゅ、みゅ、Müllる", 3, 20)
	
	courseTrialA3 = UnlockEvent.objects.create(name="COURSE TRIAL A3", ordering=10)  # deliberately at the top, after CT A20+
	songUnlock(19, courseTrialA3, "TRIPLET", "PERSIAN LAND", [3], 10)
	songUnlock(19, courseTrialA3, "NIPPON-NO-MATSURI", "ON-DO", [3], 20)
	songUnlock(19, courseTrialA3, "FEELING", "Come Back to Me (Feel It)", [3], 30)
	songUnlock(19, courseTrialA3, "CYBER", "Debug Dance", [3], 40)
	songUnlock(19, courseTrialA3, "INTENSE", "Get it", [3], 50)
	songUnlock(19, courseTrialA3, "EXCITING WINTER", "Crystarium", [3], 60)
	songUnlock(19, courseTrialA3, "SHED TEARS", "insist", [3], 70)

	grandPrix = UnlockEvent.objects.create(name="GRAND PRIX Advance Play", ordering=175)  # deliberately above other A3
	
	vol7 = UnlockTask.objects.create(event=grandPrix, name="GRAND PRIX music pack vol.7", ordering=10)
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart('Closer to my Heart (jun remix)', 3))
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart('DOUBLE TORNARD', 3))
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart('I WANT YOUR LOVE (Darwin remix)', 3))
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart('Mess With My Emotions', 3))
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart("TRUE♥LOVE (Clubstar's True Club Mix)", 3))
	ChartUnlock.objects.create(version_id=19, task=vol7, chart=findChart('鏡花水月楼 (DDR EDITION)', 3))

	jubeat1 = UnlockTask.objects.create(event=grandPrix, name="SPECIAL music pack feat.jubeat vol.1", ordering=20)
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("glacia", 2))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("glacia", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("Megalara Garuda", 2))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("Megalara Garuda", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("Megalara Garuda", 4))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("Wowie Zowie!", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("ナナホシ", 3))
	jubeat2 = UnlockTask.objects.create(event=grandPrix, name="SPECIAL music pack feat.jubeat vol.2", ordering=25)
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("ALBIDA", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("Glitter Flatter Scatter", 2))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("Glitter Flatter Scatter", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("Too Late Snow", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("量子の海のリントヴルム", 2))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("量子の海のリントヴルム", 3))
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("量子の海のリントヴルム", 4))
	# challenge requires both packs:
	ChartUnlock.objects.create(version_id=19, task=jubeat2, chart=findChart("Megalara Garuda", 4))
	ChartUnlock.objects.create(version_id=19, task=jubeat1, chart=findChart("量子の海のリントヴルム", 4))

	softpad = UnlockTask.objects.create(event=grandPrix, name="Soft pad pre-order", ordering=30)
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Are U Ready", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Concertino in Blue", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("concon", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Get Your Wish", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Last Summer", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("perditus†paradisus", 2))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("perditus†paradisus", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Settin' the Scene", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Unity", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("VALLIS-NERIA", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("Wuv U", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("サヨナラ・ヘヴン", 3))
	ChartUnlock.objects.create(version_id=19, task=softpad, chart=findChart("ヤサイマシ☆ニンニクアブラオオメ", 3))

	vol10 = UnlockTask.objects.create(event=grandPrix, name="GRAND PRIX music pack vol.10", ordering=40)
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("CANDY (UFO mix)", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("Curry Up", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("Heavens and the Earth", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("PARADISE", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("STAY (Joey Riot remix)", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("Take Me", 3))
	ChartUnlock.objects.create(version_id=19, task=vol10, chart=findChart("We Will Live Together", 3))

	touhou1 = UnlockTask.objects.create(event=grandPrix, name="SPECIAL music pack feat.Touhou Project vol.1", ordering=50)
	ChartUnlock.objects.create(version_id=19, task=touhou1, chart=findChart("リスペク風神", 3))
	ChartUnlock.objects.create(version_id=19, task=touhou1, chart=findChart("最速最高シャッターガール", 3))
	ChartUnlock.objects.create(version_id=19, task=touhou1, chart=findChart("最速最高シャッターガール", 4))
	touhou2 = UnlockTask.objects.create(event=grandPrix, name="SPECIAL music pack feat.Touhou Project vol.2", ordering=55)
	ChartUnlock.objects.create(version_id=19, task=touhou2, chart=findChart("恋の氷結おてんば湯けむりチルノ温泉", 3))
	ChartUnlock.objects.create(version_id=19, task=touhou2, chart=findChart("スカーレット警察のゲットーパトロール24時", 3))
	ChartUnlock.objects.create(version_id=19, task=touhou2, chart=findChart("スカーレット警察のゲットーパトロール24時", 4))
	# challenge requires both packs:
	ChartUnlock.objects.create(version_id=19, task=touhou2, chart=findChart("最速最高シャッターガール", 4))
	ChartUnlock.objects.create(version_id=19, task=touhou1, chart=findChart("スカーレット警察のゲットーパトロール24時", 4))

	vol13 = UnlockTask.objects.create(event=grandPrix, name="GRAND PRIX music pack vol.13", ordering=60)
	vol14 = UnlockTask.objects.create(event=grandPrix, name="GRAND PRIX music pack vol.14", ordering=65)
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("Be With You (Still Miss you)", 3))
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("little steps", 3))
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("On the Night of a Still Wind", 3))
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("Such A Feeling", 3))
	# challenge charts for existing songs, requiring two packs to be purchased (what the _fuck_ konami)
	ChartUnlock.objects.create(version_id=19, task=vol13, chart=findChart("CRAZY♥LOVE", 4))
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("CRAZY♥LOVE", 4))
	ChartUnlock.objects.create(version_id=19, task=vol13, chart=findChart("Wow Wow VENUS", 4))
	ChartUnlock.objects.create(version_id=19, task=vol14, chart=findChart("Wow Wow VENUS", 4))

	musicChoice = UnlockEvent.objects.create(name="DANCE aROUND × DanceDanceRevolution 2022 natsu no MUSIC CHOICE", ordering=230)
	songUnlock(19, musicChoice, "Prettiful!", "Prettiful!", [3], 10)
	songUnlock(19, musicChoice, "Go Down", "Go Down", [3], 20)
	songUnlock(19, musicChoice, "You You You", "You You You", [3], 30)
	songUnlock(19, musicChoice, "Easy Peasy", "Easy Peasy", [3], 40)
	songUnlock(19, musicChoice, "Acid,Tribal & Dance (DDR EDITION)", "Acid,Tribal & Dance (DDR EDITION)", [3, 4], 50)

	mixUp = UnlockEvent.objects.create(name="いちかのごちゃまぜMix UP！", ordering=240)
	step1 = UnlockTask.objects.create(event=mixUp, name="Step 1", ordering=10)
	ChartUnlock.objects.create(version_id=19, task=step1, chart=findChart("キヤロラ衛星の軌跡", 3))
	ChartUnlock.objects.create(version_id=19, task=step1, chart=findChart("BREDLI", 3))
	step2 = UnlockTask.objects.create(event=mixUp, name="Step 2", ordering=20)
	ChartUnlock.objects.create(version_id=19, task=step2, chart=findChart("Kilonova", 3))
	ChartUnlock.objects.create(version_id=19, task=step2, chart=findChart("新蛇姫", 2))
	ChartUnlock.objects.create(version_id=19, task=step2, chart=findChart("新蛇姫", 3))
	songUnlock(19, mixUp, "Final Song", "VOLAQUAS", [2, 3], 30)


def backward(apps, schema_editor):
	# These are the first unlock events/tasks to ever be created, so deleting them all is safe.
	# Event cascades to task, which cascades to Chart- and PlayerUnlock, so deleting all tasks
	# is sufficient to start over.
	UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
	UnlockEvent.objects.all().delete()

class Migration(migrations.Migration):
	dependencies = [('scorebrowser', '0016_cabinet_data')]

	operations = [migrations.RunPython(forward, backward)]