# Generated by Django 3.2.16 on 2023-02-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0017_event_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songvisibilitypreference',
            name='gold_visibility',
        ),
        migrations.RemoveField(
            model_name='songvisibilitypreference',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songvisibilitypreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='songvisibilitypreference',
            name='white_visibility',
        ),
        migrations.DeleteModel(
            name='SongVisibility',
        ),
        migrations.DeleteModel(
            name='SongVisibilityPreference',
        ),
    ]
