# Generated by Django 3.2.16 on 2023-02-07 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0019_auto_20230206_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.cabinetmodel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.region')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.version')),
            ],
        ),
    ]
