# Generated by Django 3.2.16 on 2023-02-11 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0022_challenge_charts_a3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal_chart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.chart'),
        ),
    ]
