# Generated by Django 3.2.16 on 2023-04-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0040_golden_league_cabinet_locks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='raw_spice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goal_benchmark',
        ),
    ]
