# Generated by Django 3.2.16 on 2023-06-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0054_course_trial_mentanpindoradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='alternate_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='romanized_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='searchable_title',
            field=models.TextField(default=''),
        ),
    ]
