# Generated by Django 3.2.16 on 2023-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0074_triple_tribe_locked_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='tracked',
            field=models.BooleanField(default=True),
        ),
    ]
