# Generated by Django 3.2.16 on 2023-09-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0077_kac_round_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='user_default',
            field=models.BooleanField(default=False),
        ),
    ]
