# Generated by Django 3.2.16 on 2023-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0080_music_choice_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='romanized_titles',
            field=models.BooleanField(default=False),
        ),
    ]
