# Generated by Django 3.2.16 on 2023-09-29 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0081_user_romanized_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChartNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.chart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.user')),
            ],
        ),
    ]
