# Generated by Django 3.2.16 on 2023-10-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0083_gp10_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChartBookmarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.chart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.user')),
            ],
        ),
    ]
