# Generated by Django 3.2.16 on 2023-10-08 19:12

from django.db import migrations

def forward(apps, schema_editor):
    SongLock = apps.get_model("scorebrowser", "SongLock")
    Song = apps.get_model("scorebrowser", "Song")
    CabinetModel = apps.get_model("scorebrowser", "CabinetModel")

    titles = [
        "Sector",
        "Ability",
        "SURVIVAL AT THE END OF THE UNIVERSE",
        "Jungle Dance",
        "Rave in the Shell",
        "Not Alone",
    ]

    def findSong(title):
        candidates = Song.objects.filter(title=title)
        for song in candidates:
            if song.title == title:
                return song

    gold = CabinetModel.objects.get(name='gold')

    for title in titles:
        SongLock.objects.create(model=gold, song=findSong(title))


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0085_userchartaux'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
