# Generated by Django 3.2.16 on 2023-10-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0088_fix_gl_cab'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchartaux',
            name='life4_clear',
            field=models.BooleanField(default=False),
        ),
    ]
