# Generated by Django 3.2.16 on 2023-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0090_auto_20231025_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockevent',
            name='amethyst_required',
            field=models.BooleanField(default=True),
        ),
    ]
