# Generated by Django 3.2.16 on 2023-10-31 03:59

from django.db import migrations

def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")

    for name in [
        "New Challenge charts (A3)",
        '[A20 PLUS] FLOOR INFECTION',
        '[A20 PLUS] DDR CHALLENGE Carnival PLUS',
        '[A20 PLUS] The 10th KONAMI Arcade Championship Entry Song',
        '[A20 PLUS] BPL応援 楽曲解禁スタンプラリー',
        '[A20 PLUS] BEMANI 2021真夏の歌合戦5番勝負',
    ]:
        event = UnlockEvent.objects.get(name=name)
        event.amethyst_required = False
        event.save()

def backward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")

    for name in [
        "New Challenge charts (A3)",
        '[A20 PLUS] FLOOR INFECTION',
        '[A20 PLUS] DDR CHALLENGE Carnival PLUS',
        '[A20 PLUS] The 10th KONAMI Arcade Championship Entry Song',
        '[A20 PLUS] BPL応援 楽曲解禁スタンプラリー',
        '[A20 PLUS] BEMANI 2021真夏の歌合戦5番勝負',
    ]:
        event = UnlockEvent.objects.get(name=name)
        event.amethyst_required = True
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0093_life4_rank_bugfix'),
    ]

    operations = [migrations.RunPython(forward, backward)]
