# Generated by Django 3.2.16 on 2023-11-08 03:12

from django.db import migrations

def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")

    kac = UnlockEvent.objects.get(name="[A3] KONAMI Arcade Championship (2023) Entry Songs")
    for unlock in ChartUnlock.objects.filter(task__event=kac):
        unlock.extra = False
        unlock.save() 

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0095_unlocks_handle_unspiced_charts'),
    ]

    operations = [migrations.RunPython(forward, backward)]
