# Generated by Django 3.2.16 on 2023-11-15 05:29

from django.db import migrations


def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")

    def findCharts(title):
        candidates = Chart.objects.filter(song__title=title)
        return [c for c in candidates if (c.song.title == title)]

    def createExtraSaviors(version_id, event, title, firstOrdering):
        taskOrdering = firstOrdering
        for chart in findCharts(title):
            task = UnlockTask.objects.create(event=event, name='{} ({} {})'.format(title, chart.difficulty.name, chart.rating), ordering=taskOrdering)
            ChartUnlock.objects.create(version_id=version_id, task=task, chart=chart, extra=True)
            taskOrdering += 10
        return taskOrdering

    trickOrTreat = UnlockEvent.objects.create(name="Boo! Trick or treat!", ordering=205)
    nextOrdering = createExtraSaviors(19, trickOrTreat, '惑星☆ロリポップ', 0)
    nextOrdering = createExtraSaviors(19, trickOrTreat, 'BONE BORN', nextOrdering)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0097_babylons_galaxy_and_other_updates'),
    ]

    operations = [migrations.RunPython(forward, backward)]
