# Generated by Django 3.2.16 on 2023-11-17 03:14

from django.db import migrations

def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")

    babylon = UnlockEvent.objects.get(name="BABY-LON'S GALAXY")
    babylon.amethyst_required = False
    babylon.save()

    bird = UnlockEvent.objects.get(name="BABY-LON'S GALAXY ENCORE EXTRA STAGE")
    bird.amethyst_required = False
    babylon.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0098_boo_trick_or_treat'),
    ]

    operations = [migrations.RunPython(forward, backward)]
