# Generated by Django 3.2.16 on 2023-11-17 03:27

from django.db import migrations


def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")

    wakuseiExpert = UnlockTask.objects.get(name="惑星☆ロリポップ (Expert 15)")
    wakuseiExpert.ordering = 40
    wakuseiExpert.save()

    boneBornExpert = UnlockTask.objects.get(name="BONE BORN (Expert 13)")
    boneBornExpert.ordering = 80
    boneBornExpert.save()
    
    event = UnlockEvent.objects.get(name="Boo! Trick or treat!")
    event.name = "[A3] Boo! Trick or treat!"
    event.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0100_course_trial_cheer_up'),
    ]

    operations = [migrations.RunPython(forward, backward)]
