# Generated by Django 3.2.16 on 2023-11-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0101_trick_or_treat_reordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_rank',
            field=models.IntegerField(default=0),
        ),
    ]
