# Generated by Django 3.2.16 on 2023-12-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0105_gp_touhou_1_2_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequirementTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.user')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.version')),
            ],
        ),
    ]
