# Generated by Django 3.2.16 on 2023-12-22 03:22

from django.db import migrations


def forward(apps, schema_editor):
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")

    def findChart(title, difficulty_id):
        candidates = Chart.objects.filter(song__title=title, difficulty_id=difficulty_id)
        for chart in candidates:
            if chart.song.title == title: # 'take me higher' / 'TAKE ME HIGHER' sql collation woes
                return chart
        return None

    birdTask = UnlockTask.objects.get(name="Phoenix")
    ChartUnlock.objects.create(version_id=19, task=birdTask, chart=findChart("鳳", 3), extra=True)
    ChartUnlock.objects.create(version_id=19, task=birdTask, chart=findChart("鳳", 2), extra=True)
    ChartUnlock.objects.create(version_id=19, task=birdTask, chart=findChart("鳳", 1), extra=True)
    ChartUnlock.objects.create(version_id=19, task=birdTask, chart=findChart("鳳", 0), extra=True)

def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0110_gp_23_24_hinabitter'),
    ]

    operations = [migrations.RunPython(forward, backward)]
