# Generated by Django 3.2.16 on 2023-12-24 00:43

from django.db import migrations

def forward(apps, schema_editor):
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    doubles = UnlockTask.objects.get(name="All of the above, on doubles")
    doubles.ordering = 1000
    doubles.save()

def backward(apps, schema_editor):
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0111_phoenix_charts'),
    ]

    operations = [migrations.RunPython(forward, backward)]
