# Generated by Django 3.2.16 on 2023-12-24 01:01

from django.db import migrations

def forward(apps, schema_editor):
    Event = apps.get_model("scorebrowser", "Event")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")

    for event in Event.objects.all():
        versions = set(u.version for u in ChartUnlock.objects.filter(task__event=event))
        if len(versions) != 1:
            raise Exception("Event {} has {} versions in its unlocks (need 1)".format(event.name, len(versions)))
        event.version = next(iter(versions))


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0114_unlockevent_version'),
    ]

    operations = [
    # there's no operations here, this code didn't run
    ]
