# Generated by Django 3.2.16 on 2023-12-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0115_version_from_unlock_to_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartunlock',
            name='version',
        ),
    ]
