# Generated by Django 3.2.16 on 2023-12-24 01:19

from django.db import migrations

def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")

    a3Events = [
        "EXTRA EXCLUSIVE",
        "New Challenge charts (A3)",
        "GOLDEN LEAGUE A3",
        "[A3] EXTRA SAVIOR A3",
        "[A3] Enjoy Summer Vacation!",
        "[A3] BEMANI 2021真夏の歌合戦5番勝負 (wave 1)",
        "[A3] Crystal clear winter",
        "[A3] 恋せよDDRのバレンタイン＆ホワイトデー2023",
        "[A3] COURSE TRIAL A3",
        "GRAND PRIX Advance Play",
        "[A3] いちかのごちゃまぜMix UP！",
        "bag Challenge should not exist",
        "[A3] 春を呼ぶ桜の祝祭",
        "[A3] KONAMI Arcade Championship (2023) Entry Songs",
        "[A3] BEMANI PRO LEAGUE -SEASON 3- Triple Tribe",
        "[A3] DANCE aROUND × DanceDanceRevolution 2022 natsu no MUSIC CHOICE",
        "[A3] BEMANI 2021真夏の歌合戦5番勝負 (wave 2)",
        "BABY-LON'S GALAXY",
        "BABY-LON'S GALAXY ENCORE EXTRA STAGE",
        "[A3] Boo! Trick or treat!",
    ]
    for event in UnlockEvent.objects.all():
        version_id = 19 if event.name in a3Events else 18
        event.version_id = version_id
        event.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0116_remove_chartunlock_version'),
    ]

    operations = [migrations.RunPython(forward, backward)]
