# Generated by Django 3.2.16 on 2023-12-31 04:03

from django.db import migrations


def forward(apps, schema_editor):
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")

    e = UnlockEvent.objects.get(name="New Challenge charts (A3)")
    e.version_id = 18
    e.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0118_gl_rotate_euphoric_for_realsies'),
    ]

    operations = [migrations.RunPython(forward, backward)]
