# Generated by Django 3.2.16 on 2024-03-27 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorebrowser', '0127_gl_rotate_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='django_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
