# Generated by Django 4.2.7 on 2024-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0141_kac_2023_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='quality',
            field=models.FloatField(default=None, null=True),
        ),
    ]
