# Generated by Django 4.2.7 on 2024-07-23 02:36

from django.db import migrations

def forward(apps, schema_editor):
    Version = apps.get_model("scorebrowser", "Version")
    Version.objects.create(id=20, name="WORLD")

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0143_triple_tribe_2_gold'),
    ]

    operations = [migrations.RunPython(forward, backward)]
