# Generated by Django 4.2.7 on 2024-07-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0144_world_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
