# Generated by Django 4.2.7 on 2024-08-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0146_bpl_s2_all_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockevent',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
    ]
