# Generated by Django 4.2.7 on 2024-08-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0148_world_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressiveUnlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.unlockevent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.unlocktask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorebrowser.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprogressiveunlock',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='uniq_progressive'),
        ),
    ]
