# Generated by Django 4.2.7 on 2024-09-13 03:24

from django.db import migrations


def forward(apps, schema_editor):
    Chart = apps.get_model("scorebrowser", "Chart")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockGroup = apps.get_model("scorebrowser", "UnlockGroup")
    
    group = UnlockGroup.objects.get(name="Time-limited events")
    event = UnlockEvent.objects.create(
        version_id=20,
        group=group,
        name="MYSTICAL Re:UNION",
        progressive=True,
        ordering=0,
    )

    def findChart(title, difficulty_id):
        candidates = Chart.objects.filter(song__title=title, difficulty_id=difficulty_id)
        for chart in candidates:
            if chart.song.title == title: # 'take me higher' / 'TAKE ME HIGHER' sql collation woes
                return chart
        return None

    def makeUnlock(points, title):
        task = UnlockTask.objects.create(event=event, name="{} BRS & BRD ({})".format(points, title), ordering=points)
        for difficulty_id in [0, 1, 2, 3]:
            ChartUnlock.objects.create(task=task, chart=findChart(title, difficulty_id))

    makeUnlock(250, "Blφφdy Cφncertφ")
    makeUnlock(600, "OROCHI STRIKE")
    makeUnlock(1500, "Lichtsäule")
    makeUnlock(3750, "REINCARNATION")
    makeUnlock(4000, "Re:RHYZE")

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0153_triple_tribe_challenge_oops'),
    ]

    operations = [migrations.RunPython(forward, backward)]
