# Generated by Django 4.2.7 on 2024-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0155_reunion_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='normalized',
            field=models.FloatField(default=0),
        ),
    ]
