# Generated by Django 4.2.7 on 2024-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0156_score_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='normscore_breakpoints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chart',
            name='quality_breakpoints',
            field=models.TextField(default=''),
        ),
    ]
