# Generated by Django 4.2.7 on 2024-09-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0157_chart_normscore_breakpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='normalized',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='UnprocessedPair',
        ),
    ]
