# Generated by Django 4.2.7 on 2024-10-05 19:38

from django.db import migrations, models
from scorebrowser.misc import sort_key


def forward(apps, schema_editor):
    Song = apps.get_model("scorebrowser", "Song")

    all_songs = Song.objects.all()
    for song in all_songs:
        song.sort_key = sort_key(song.searchable_title or song.title)
    Song.objects.bulk_update(all_songs, ['sort_key'])


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0160_gp_31_32_bemani_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='sort_key',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(forward, backward),
    ]
