# Generated by Django 4.2.7 on 2024-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0161_song_sort_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='low_conf',
            field=models.BooleanField(default=False),
        ),
    ]
