# Generated by Django 4.2.7 on 2024-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0163_userscore_flare_gauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_flare',
            field=models.IntegerField(default=0),
        ),
    ]
