# Generated by Django 3.2.16 on 2024-02-16 06:12

from django.db import migrations


def forward(apps, schema_editor):
    UnlockGroup = apps.get_model("scorebrowser", "UnlockGroup")
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")

    def findCharts(title):
        candidates = Chart.objects.filter(song__title=title)
        if len(candidates) == 0:
            raise Exception("No charts found for {}".format(title))
        return [c for c in candidates if (c.song.title == title)]

    def songUnlock(event, taskName, title, taskOrdering):
        task = UnlockTask.objects.create(event=event, name=taskName, ordering=taskOrdering)
        for chart in findCharts(title):
            ChartUnlock.objects.create(task=task, chart=chart)

    group = UnlockGroup.objects.get(name="Time-limited events")
    tripleTribe = UnlockEvent.objects.create(
        version_id=20,
        group=group,
        name='BEMANI PRO LEAGUE -SEASON 3- Triple Tribe',
        ordering=-10,
        amethyst_required=False,
    )
    songUnlock(tripleTribe, 'Part 2 - 700 TB (コメット⇒スケイター)', 'コメット⇒スケイター', 30)
    songUnlock(tripleTribe, 'Part 2 - 1400 TS (3y3s)', '3y3s', 40)
    songUnlock(tripleTribe, 'Part 2 - 2100 each (Ambivalent Vermilia)', 'Ambivalent Vermilia', 50)

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [('scorebrowser', '0164_user_selected_flare')]

    operations = [migrations.RunPython(forward, backward)]