# Generated by Django 4.2.7 on 2025-04-19 04:38

from django.db import migrations
from django.db.models import Max



def forward(apps, schema_editor):
    UnlockGroup = apps.get_model("scorebrowser", "UnlockGroup")
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")

    def findCharts(title):
        candidates = Chart.objects.filter(song__title=title).filter(hidden=False).order_by("difficulty_id")
        if candidates.count() == 0:
            raise ValueError("No charts found for {}".format(title))
        return [c for c in candidates if (c.song.title == title)]

    def createExtraSaviors(event, title):
        for chart in findCharts(title):
            task = UnlockTask.objects.create(event=event, name='{} ({} {})'.format(title, chart.difficulty.name, chart.rating), ordering=createExtraSaviors.nextOrdering)
            ChartUnlock.objects.create(task=task, chart=chart, extra=True)
            createExtraSaviors.nextOrdering += 10
    createExtraSaviors.nextOrdering = 0

    ordering = UnlockEvent.objects.aggregate(Max('ordering'))['ordering__max'] + 10
    extraSavior = UnlockGroup.objects.get(name="Extra Savior")
    phase1 = UnlockEvent.objects.create(
        version_id=20,
        group=extraSavior,
        name="BEMANI SELECTION vol.2 phase 1 songs",
        ordering=ordering,
    )
    createExtraSaviors(phase1, "Chocolate Planet")
    createExtraSaviors(phase1, "Four Leaves")
    createExtraSaviors(phase1, "Ganymede -re:born-")
    createExtraSaviors(phase1, "童話回廊")
    createExtraSaviors(phase1, "リメンバーリメンバー")

    ordering += 10
    phase2 = UnlockEvent.objects.create(
        version_id=20,
        group=extraSavior,
        name="BEMANI SELECTION vol.2 phase 2 songs",
        ordering=ordering,
    )
    createExtraSaviors(phase2, "Bad Maniacs")
    createExtraSaviors(phase2, "Timepiece phase Ⅱ")
    createExtraSaviors(phase2, "恋歌疾風！かるたクイーンいろは")

def backward(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0180_gp_bemani_1_unlocked'),
    ]

    operations = [migrations.RunPython(forward, backward)]
