# Generated by Django 4.2.7 on 2025-06-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0184_platinum_and_many_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisibility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
