# Generated by Django 4.2.7 on 2025-06-22 22:53

from django.db import migrations



def forward(apps, schema_editor):
    ProfileVisibility = apps.get_model("scorebrowser", "ProfileVisibility")
    ProfileVisibility.objects.create(id=0, name="Private")
    ProfileVisibility.objects.create(id=1, name="Admin")
    ProfileVisibility.objects.create(id=2, name="Public")

def backward(apps, schema_editor):
    pass    

class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0185_profilevisibility'),
    ]

    operations = [migrations.RunPython(forward, backward)]
