# Generated by Django 4.2.7 on 2025-06-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0186_profilevisibility_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='scorebrowser.profilevisibility'),
        ),
    ]
