# Generated by Django 4.2.7 on 2025-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0187_user_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisibility',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
