# Generated by Django 4.2.7 on 2025-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0188_profilevisibility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reauth',
            field=models.BooleanField(default=False),
        ),
    ]
