# Generated by Django 4.2.7 on 2025-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0189_user_reauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vis_asked',
            field=models.BooleanField(default=False),
        ),
    ]
