# Generated by Django 4.2.7 on 2025-07-24 02:40

from django.db import migrations

def forward(apps, schema_editor):
    User = apps.get_model("scorebrowser", "User")
    User.objects.exclude(visibility_id=0).update(vis_asked=True)

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0190_user_vis_asked'),
    ]

    operations = [migrations.RunPython(forward, backward)]
