# Generated by Django 4.2.25 on 2025-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0196_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockevent',
            name='amethyst_required',
            field=models.BooleanField(default=False),
        ),
    ]
