# Generated by Django 4.2.25 on 2026-01-01 00:13

from django.db import migrations
from django.db.models import Max


def forward(apps, schema_editor):
    UnlockGroup = apps.get_model("scorebrowser", "UnlockGroup")
    UnlockEvent = apps.get_model("scorebrowser", "UnlockEvent")
    UnlockTask = apps.get_model("scorebrowser", "UnlockTask")
    ChartUnlock = apps.get_model("scorebrowser", "ChartUnlock")
    Chart = apps.get_model("scorebrowser", "Chart")
    Difficulty = apps.get_model("scorebrowser", "Difficulty")

    def findCharts(title):
        candidates = Chart.objects.filter(song__title=title).order_by("difficulty_id")
        if len(candidates) == 0:
            raise Exception("No charts found for {}".format(title))
        return [c for c in candidates if (c.song.title == title)]

    def createExtraSaviors(event, title):
        for chart in findCharts(title):
            task = UnlockTask.objects.create(event=event, name='{} ({} {})'.format(title, chart.difficulty.name, chart.rating), ordering=createExtraSaviors.nextOrdering)
            ChartUnlock.objects.create(task=task, chart=chart, extra=True)
            createExtraSaviors.nextOrdering += 10
    createExtraSaviors.nextOrdering = 0

    ordering = UnlockEvent.objects.aggregate(Max('ordering'))['ordering__max'] + 10
    extraSavior = UnlockGroup.objects.get(name="Extra Savior")
    bemani1 = UnlockEvent.objects.create(
        version_id=20,
        group=extraSavior,
        name="BEMANI SELECTION vol.3 phase 1 songs",
        ordering = ordering,
    )
    createExtraSaviors(bemani1, "CUE CUE RESCUE")
    createExtraSaviors(bemani1, "O JIYA")
    createExtraSaviors(bemani1, "朱と碧のランページ")
    createExtraSaviors(bemani1, "水槽のクジラ")
    createExtraSaviors(bemani1, "ミカヅキ:コネクト")

    bemani2 = UnlockEvent.objects.create(
        version_id=20,
        group=extraSavior,
        name="BEMANI SELECTION vol.3 phase 2 songs",
        ordering = ordering + 10,
    )
    createExtraSaviors(bemani2, "BIGソムタム")
    createExtraSaviors(bemani2, "月光乱舞")
    createExtraSaviors(bemani2, "シャムシールの舞")


    def rotate(goldTitles, silverTitles, bronzeTitles, defaultTitles):
        bronze = UnlockTask.objects.get(event__name="WORLD LEAGUE", name="BRONZE CLASS").id
        silver = UnlockTask.objects.get(event__name="WORLD LEAGUE", name="SILVER CLASS").id
        gold = UnlockTask.objects.get(event__name="WORLD LEAGUE", name="GOLD CLASS").id
        advance = UnlockTask.objects.get(event__name="WORLD LEAGUE", name="GOLD CLASS with advanced border").id

        for goldTitle in goldTitles:
            goldUnlocks = ChartUnlock.objects.filter(task_id=advance, chart__song__title=goldTitle)
            for unlock in goldUnlocks:
                if unlock.chart.song.title == goldTitle:
                    unlock.task_id = gold
                    unlock.save()

        for silverTitle in silverTitles:
            silverUnlocks = ChartUnlock.objects.filter(task_id=gold, chart__song__title=silverTitle)
            for unlock in silverUnlocks:
                if unlock.chart.song.title == silverTitle:
                    unlock.task_id = silver
                    unlock.save()

        for bronzeTitle in bronzeTitles:
            bronzeUnlocks = ChartUnlock.objects.filter(task_id=silver, chart__song__title=bronzeTitle)
            for unlock in bronzeUnlocks:
                if unlock.chart.song.title == bronzeTitle:
                    unlock.task_id = bronze
                    unlock.save()

        for defaultTitle in defaultTitles:
            defaultUnlocks = ChartUnlock.objects.filter(task_id=bronze, chart__song__title=defaultTitle)
            for unlock in defaultUnlocks:
                if unlock.chart.song.title == defaultTitle:
                    unlock.delete()
    rotate(["BRAIN-HEART"], [""], [""], [])

    advanceBorder = UnlockTask.objects.get(event__name="WORLD LEAGUE", name="GOLD CLASS with advanced border")
    def newGoldenLeague(new_title):
        for c in findCharts(new_title):
            ChartUnlock.objects.create(task=advanceBorder, chart=c)
    newGoldenLeague("Be Happy Next 2 You")



def backward(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0201_challenge_charts_2025_12'),
    ]

    operations = [migrations.RunPython(forward, backward)]
