# Generated by Django 4.2.26 on 2026-02-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0202_bemani_selection_3_gl_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_fetch',
            field=models.DateTimeField(null=True),
        ),
    ]
