# Generated by Django 4.2.26 on 2026-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebrowser', '0203_user_last_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
