name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./pprxweb

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SECRET_KEY: "test"
        CLIENT_ID: "test"
        CLIENT_SECRET: "test"
        GOOGLE_USERNAME: "test"
        GOOGLE_APP_PASSWORD: "test"
      run: |
        python manage.py test
